"""A generated Seedance clip must never be left out of the film.

Owner 2026-08-21: "generated video seedance is not picked up since the plan
says depthflow, we should give seedance higher priority in any case."

The community assembler has been AI-first since 2026-08-17; the home-tour one
was written preferring the PLANNED engine, so a paid clip generated by hand sat
unused whenever the plan had settled on DepthFlow for that photo. The one
engine whose output must never be wasted was the one most easily ignored, and
nothing said so — the film just quietly came out without it.
"""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO / "scripts" / "render-worker"))


def pick_clip(candidates, planned):
    """Mirror of worker.pick_clip.

    Copied rather than imported: `worker` pulls in numpy, requests and a live
    Supabase config at import time. The function is six lines and pure, and the
    parametrised cases below are the contract either copy has to meet.
    """
    if not candidates:
        return None
    return (
        next((c for c in candidates if c.get("engine") == "seedance"), None)
        or next((c for c in candidates if c.get("engine") == planned), None)
        or candidates[0]
    )


def clip(engine):
    return {"engine": engine, "storage_path": f"clips/{engine}.mp4"}


def test_seedance_wins_over_the_planned_engine():
    # The reported case, exactly: plan says depthflow, a seedance clip exists.
    got = pick_clip([clip("depthflow"), clip("seedance")], "depthflow")
    assert got["engine"] == "seedance"


def test_seedance_wins_regardless_of_candidate_order():
    assert pick_clip([clip("seedance"), clip("kenburns")], "kenburns")["engine"] == "seedance"
    assert pick_clip([clip("kenburns"), clip("seedance")], "kenburns")["engine"] == "seedance"


def test_seedance_wins_even_when_the_plan_named_something_absent():
    got = pick_clip([clip("seedance"), clip("kenburns")], "depthflow")
    assert got["engine"] == "seedance"


def test_falls_back_to_the_planned_engine_when_there_is_no_ai_clip():
    got = pick_clip([clip("kenburns"), clip("depthflow")], "depthflow")
    assert got["engine"] == "depthflow"


def test_falls_back_to_anything_ready_when_the_planned_engine_is_missing():
    # A shot planned for DepthFlow still renders from the Ken Burns clip the
    # photo already has, rather than dropping out of the film.
    got = pick_clip([clip("kenburns")], "depthflow")
    assert got["engine"] == "kenburns"


def test_no_candidates_is_none_not_a_crash():
    # The caller skips the shot on None. Returning candidates[0] off an empty
    # list is how this raises IndexError inside a job instead.
    assert pick_clip([], "kenburns") is None


def test_an_unplanned_shot_still_gets_a_clip():
    assert pick_clip([clip("kenburns")], None)["engine"] == "kenburns"
