/**
 * The move-in question bank — `docs/design/move-in-questions.md` §3 as data.
 *
 * Shared because both sides read it: the web generation job asks a model to
 * answer these questions for a listing (and validates its output against the
 * allow-lists here), and the mobile explore page renders the question text,
 * groups by theme, and ranks. A question id is a stable contract — events
 * and stored answers reference it — so entries are never renamed, only added.
 *
 * The doc is the source of truth for WHY each row is shaped as it is; this
 * file carries only what code needs. Keep the two in step.
 *
 * Fair Housing (doc §1.3): `fh: 'never'` rows are reserved questions we do
 * not ask. They are listed so the omission is a decision, not an oversight;
 * generation must skip them and the UI must never render them.
 */

import type { DimKey } from './types';

export type QuestionTheme =
  | 'vibe'
  | 'people'
  | 'culture'
  | 'third'
  | 'kids'
  | 'pets'
  | 'body'
  | 'nature'
  | 'work'
  | 'money'
  | 'safety'
  | 'logistics'
  | 'house'
  | 'sound'
  | 'identity'
  | 'future';

/** Cache / generation granularity (doc §1.5). */
export type QuestionScope = 'home' | 'street' | 'hood' | 'city';

export type QuestionAudience =
  | 'all'
  | 'family'
  | 'single'
  | 'couple'
  | 'downsizer'
  | 'immigrant'
  | 'investor'
  | 'remote'
  | 'commuter'
  | 'pet'
  | 'multigen'
  | 'first_time'
  | 'accessibility'
  | 'athlete'
  | 'gardener';

/** What an answer may rest on (doc §2.1). Arrays so zod can enum them. */
export const BASIS_TYPES = [
  'road',
  'dist',
  'place',
  'school',
  'transit',
  'project',
  'zoning',
  'assessor',
  'mls',
  'listing_text',
  'photo',
  'hazard',
  'climate',
  'utility',
  'crime',
  'civic',
  'tenure',
  'social',
  'market',
] as const;
export type BasisType = (typeof BASIS_TYPES)[number];

/**
 * Basis types that are claims about the world and therefore need a source
 * URL. The rest are measurements or the listing's own record, which the
 * generator can state without a link (a distance it computed, the year built).
 */
export const SOURCED_BASIS_TYPES: readonly BasisType[] = [
  'school',
  'transit',
  'project',
  'zoning',
  'hazard',
  'climate',
  'utility',
  'crime',
  'civic',
  'tenure',
  'social',
  'market',
];

export const ANSWER_FORMS = [
  'text',
  'number',
  'map',
  'quote',
  'narrative',
  'timeline',
  'checklist',
  'yes_no',
] as const;
export type AnswerForm = (typeof ANSWER_FORMS)[number];

export type FairHousing = 'n/a' | 'care' | 'never';

export interface QuestionDef {
  id: string;
  theme: QuestionTheme;
  /** Buyer's voice, second person. */
  q: string;
  who: readonly QuestionAudience[];
  scope: QuestionScope;
  basis: readonly BasisType[];
  form: AnswerForm;
  /** "Go see for yourself" template; absent when a visit cannot settle it. */
  verify?: string;
  /** Existing profile dim the question's OPENING feeds, when one fits. */
  dim?: DimKey;
  fh: FairHousing;
}

export const THEME_LABELS: Record<QuestionTheme, string> = {
  vibe: 'Vibe',
  people: 'People',
  culture: 'Culture',
  third: 'Third places',
  kids: 'Kids',
  pets: 'Pets',
  body: 'Body',
  nature: 'Nature',
  work: 'Work',
  money: 'Money',
  safety: 'Safety',
  logistics: 'Logistics',
  house: 'The house',
  sound: 'Sound',
  identity: 'Identity',
  future: 'Future',
};

/** Display order for the theme browser. */
export const THEME_ORDER: readonly QuestionTheme[] = [
  'vibe',
  'people',
  'culture',
  'third',
  'kids',
  'pets',
  'body',
  'nature',
  'work',
  'money',
  'safety',
  'logistics',
  'house',
  'sound',
  'identity',
  'future',
];

/**
 * Cold-start five (doc §4): span themes, answerable for nearly every home,
 * and each one's opening is informative about the buyer.
 */
export const COLD_START: readonly string[] = [
  'money.catch',
  'logistics.turn',
  'house.era',
  'vibe.sunday',
  'kids.zone',
];

export const QUESTIONS: readonly QuestionDef[] = [
  // ─── 3.1 Vibe ──────────────────────────────────────────────────────────
  {
    id: 'vibe.sunday',
    theme: 'vibe',
    q: 'What does this street feel like at 9am on a Sunday?',
    who: ['all'],
    scope: 'street',
    basis: ['road', 'place', 'school', 'tenure', 'social'],
    form: 'narrative',
    verify: 'Sunday 9–10am, walk the block',
    dim: 'quiet',
    fh: 'care',
  },
  {
    id: 'vibe.porch',
    theme: 'vibe',
    q: 'Do people sit out front here, or drive into the garage and close the door?',
    who: ['all'],
    scope: 'street',
    basis: ['photo', 'road', 'tenure'],
    form: 'text',
    verify: 'Weekday 6pm, drive the block slowly',
    dim: 'quiet',
    fh: 'care',
  },
  {
    id: 'vibe.halloween',
    theme: 'vibe',
    q: 'How many houses on this block do Halloween?',
    who: ['family', 'all'],
    scope: 'street',
    basis: ['social'],
    form: 'quote',
    dim: 'family',
    fh: 'care',
  },
  {
    id: 'vibe.wave',
    theme: 'vibe',
    q: 'Is this a wave-at-your-neighbour street or a never-learn-their-names street?',
    who: ['all'],
    scope: 'street',
    basis: ['tenure', 'road', 'social'],
    form: 'narrative',
    dim: 'quiet',
    fh: 'care',
  },
  {
    id: 'vibe.nextdoor',
    theme: 'vibe',
    q: "What does this neighbourhood's Nextdoor actually argue about?",
    who: ['all'],
    scope: 'hood',
    basis: ['social'],
    form: 'quote',
    dim: 'quiet',
    fh: 'care',
  },
  {
    id: 'vibe.evening',
    theme: 'vibe',
    q: 'Is anything happening here after 9pm, or is it dark and done?',
    who: ['single', 'couple'],
    scope: 'hood',
    basis: ['place', 'road'],
    form: 'text',
    verify: 'Friday 9:30pm, drive through',
    dim: 'nightlife',
    fh: 'n/a',
  },
  {
    id: 'vibe.saturday_noise',
    theme: 'vibe',
    q: 'What does Saturday morning sound like — leaf blowers, kids, nothing?',
    who: ['all'],
    scope: 'street',
    basis: ['road', 'photo', 'social'],
    form: 'text',
    verify: 'Saturday 9am, stand in the yard',
    dim: 'quiet',
    fh: 'n/a',
  },

  // ─── 3.2 People (behaviour only) ───────────────────────────────────────
  {
    id: 'people.tenure',
    theme: 'people',
    q: 'How long do people stay here — a 20-year street or a 3-year street?',
    who: ['all'],
    scope: 'street',
    basis: ['tenure', 'assessor'],
    form: 'number',
    dim: 'quiet',
    fh: 'care',
  },
  {
    id: 'people.rentals',
    theme: 'people',
    q: 'How much of this block is rentals? Any short-term rentals?',
    who: ['all'],
    scope: 'street',
    basis: ['assessor', 'zoning', 'social'],
    form: 'number',
    dim: 'quiet',
    fh: 'care',
  },
  {
    id: 'people.turnover',
    theme: 'people',
    q: "Who's moving in right now — what's the trend on this street?",
    who: ['all'],
    scope: 'hood',
    basis: ['assessor', 'market'],
    form: 'text',
    fh: 'care',
  },
  {
    id: 'people.this_house',
    theme: 'people',
    q: 'Was this house lived in by its owner, or rented out?',
    who: ['all'],
    scope: 'home',
    basis: ['mls', 'assessor'],
    form: 'text',
    verify: 'Ask the agent: tenant in place? Lease end?',
    dim: 'move_in',
    fh: 'n/a',
  },
  {
    id: 'people.single',
    theme: 'people',
    q: 'Would I feel out of place here on my own?',
    who: ['single'],
    scope: 'hood',
    basis: ['place', 'transit'],
    form: 'text',
    dim: 'nightlife',
    fh: 'care',
  },
  {
    id: 'people.downsize',
    theme: 'people',
    q: "If I'm downsizing, is there a life here without a car?",
    who: ['downsizer'],
    scope: 'hood',
    basis: ['place', 'dist', 'transit'],
    form: 'text',
    dim: 'walkable',
    fh: 'care',
  },
  {
    id: 'people.demographics',
    theme: 'people',
    q: 'Who lives here, by age / origin / religion / family?',
    who: [],
    scope: 'hood',
    basis: [],
    form: 'text',
    fh: 'never',
  },

  // ─── 3.3 Culture ───────────────────────────────────────────────────────
  {
    id: 'culture.grocery',
    theme: 'culture',
    q: "Where's the nearest grocery that carries what I actually cook with?",
    who: ['immigrant', 'all'],
    scope: 'hood',
    basis: ['place', 'dist'],
    form: 'map',
    fh: 'care',
  },
  {
    id: 'culture.worship',
    theme: 'culture',
    q: 'Is there a place of worship of my tradition within 20 minutes?',
    who: ['all'],
    scope: 'city',
    basis: ['place', 'dist'],
    form: 'map',
    fh: 'care',
  },
  {
    id: 'culture.language',
    theme: 'culture',
    q: 'Where do people who speak my language gather — school, centre, festival?',
    who: ['immigrant'],
    scope: 'city',
    basis: ['place', 'civic'],
    form: 'text',
    fh: 'care',
  },
  {
    id: 'culture.table',
    theme: 'culture',
    q: "Could I find a dim sum Sunday, a taqueria, a proper pho place, a bakery I'd drive for?",
    who: ['all'],
    scope: 'hood',
    basis: ['place'],
    form: 'map',
    dim: 'hip',
    fh: 'n/a',
  },
  {
    id: 'culture.games',
    theme: 'culture',
    q: 'Mahjong, cricket, pickup soccer, pickleball — where would I find my game?',
    who: ['all'],
    scope: 'city',
    basis: ['place', 'civic'],
    form: 'text',
    fh: 'care',
  },
  {
    id: 'culture.market',
    theme: 'culture',
    q: 'Is there a farmers market, and is it a real one or three stalls?',
    who: ['all'],
    scope: 'hood',
    basis: ['place', 'civic'],
    form: 'text',
    verify: 'Go on market day',
    dim: 'hip',
    fh: 'n/a',
  },
  {
    id: 'culture.festival',
    theme: 'culture',
    q: 'What does this town do once a year that everyone goes to?',
    who: ['all'],
    scope: 'city',
    basis: ['civic', 'social'],
    form: 'text',
    dim: 'hip',
    fh: 'n/a',
  },

  // ─── 3.4 Third places ──────────────────────────────────────────────────
  {
    id: 'third.coffee',
    theme: 'third',
    q: 'Which coffee shop would become my coffee shop?',
    who: ['all'],
    scope: 'hood',
    basis: ['place', 'dist'],
    form: 'map',
    verify: "Go at 8am Saturday, see who's there",
    dim: 'walkable',
    fh: 'n/a',
  },
  {
    id: 'third.friday',
    theme: 'third',
    q: "Is there a bar or restaurant I'd walk to on a Friday, or is every evening a drive?",
    who: ['single', 'couple'],
    scope: 'street',
    basis: ['place', 'dist', 'road'],
    form: 'text',
    dim: 'nightlife',
    fh: 'n/a',
  },
  {
    id: 'third.bump',
    theme: 'third',
    q: 'Where would I run into neighbours without planning it?',
    who: ['all'],
    scope: 'hood',
    basis: ['place', 'civic'],
    form: 'text',
    dim: 'walkable',
    fh: 'care',
  },
  {
    id: 'third.gym',
    theme: 'third',
    q: "Is there a gym, pool, climbing wall or yoga studio I'd actually use?",
    who: ['athlete', 'all'],
    scope: 'hood',
    basis: ['place', 'dist'],
    form: 'map',
    fh: 'n/a',
  },
  {
    id: 'third.library',
    theme: 'third',
    q: 'Is the library one people use, or a building?',
    who: ['family', 'downsizer'],
    scope: 'hood',
    basis: ['place', 'civic'],
    form: 'text',
    verify: 'Go on a weekday afternoon',
    dim: 'family',
    fh: 'n/a',
  },
  {
    id: 'third.dogpark',
    theme: 'third',
    q: 'Where would I take the dog to meet other dogs?',
    who: ['pet'],
    scope: 'hood',
    basis: ['place', 'dist'],
    form: 'map',
    fh: 'n/a',
  },

  // ─── 3.5 Kids ──────────────────────────────────────────────────────────
  {
    id: 'kids.friends',
    theme: 'kids',
    q: 'Would my kid have friends within bike range?',
    who: ['family'],
    scope: 'street',
    basis: ['school', 'place', 'road', 'social'],
    form: 'text',
    verify: 'Weekday 4pm, count bikes',
    dim: 'family',
    fh: 'care',
  },
  {
    id: 'kids.walk',
    theme: 'kids',
    q: 'Can my kid walk to school without crossing a busy road?',
    who: ['family'],
    scope: 'street',
    basis: ['road', 'school', 'dist'],
    form: 'map',
    verify: 'Walk it at 8:15am',
    dim: 'schools',
    fh: 'n/a',
  },
  {
    id: 'kids.bus',
    theme: 'kids',
    q: "Where's the bus stop, and can I see it from the house?",
    who: ['family'],
    scope: 'street',
    basis: ['school', 'dist'],
    form: 'map',
    dim: 'schools',
    fh: 'n/a',
  },
  {
    id: 'kids.zone',
    theme: 'kids',
    q: 'Will I drive through a school zone every day?',
    who: ['all'],
    scope: 'street',
    basis: ['school', 'road'],
    form: 'yes_no',
    verify: 'Drive it at 3:15pm',
    dim: 'quiet',
    fh: 'n/a',
  },
  {
    id: 'kids.daycare',
    theme: 'kids',
    q: "What's daycare like around here — waitlists, cost?",
    who: ['family'],
    scope: 'hood',
    basis: ['place', 'social'],
    form: 'text',
    dim: 'family',
    fh: 'n/a',
  },
  {
    id: 'kids.after',
    theme: 'kids',
    q: 'Swim team, soccer club, language school, piano — how far is each?',
    who: ['family'],
    scope: 'city',
    basis: ['place', 'dist'],
    form: 'map',
    dim: 'family',
    fh: 'care',
  },
  {
    id: 'kids.teens',
    theme: 'kids',
    q: 'Where do teenagers go here? Is there anywhere for them?',
    who: ['family'],
    scope: 'hood',
    basis: ['place', 'civic'],
    form: 'text',
    dim: 'family',
    fh: 'n/a',
  },
  {
    id: 'kids.school_change',
    theme: 'kids',
    q: 'Is a school boundary or closure about to move?',
    who: ['family'],
    scope: 'city',
    basis: ['civic', 'project'],
    form: 'timeline',
    dim: 'schools',
    fh: 'n/a',
  },
  {
    id: 'kids.school_real',
    theme: 'kids',
    q: 'The school rating says one number — what does it actually mean here?',
    who: ['family'],
    scope: 'city',
    basis: ['school', 'social'],
    form: 'text',
    dim: 'schools',
    fh: 'care',
  },
  {
    id: 'kids.pediatric',
    theme: 'kids',
    q: "Pediatrician, urgent care, children's hospital — how far?",
    who: ['family'],
    scope: 'city',
    basis: ['place', 'dist'],
    form: 'map',
    dim: 'family',
    fh: 'n/a',
  },

  // ─── 3.6 Pets ──────────────────────────────────────────────────────────
  {
    id: 'pets.walk',
    theme: 'pets',
    q: "Is there a 30-minute dog walk from the door that isn't along a busy road?",
    who: ['pet'],
    scope: 'street',
    basis: ['road', 'place', 'dist'],
    form: 'map',
    verify: 'Walk it',
    fh: 'n/a',
  },
  {
    id: 'pets.offleash',
    theme: 'pets',
    q: "Off-leash park nearby? What's the leash culture here?",
    who: ['pet'],
    scope: 'hood',
    basis: ['place', 'civic', 'social'],
    form: 'text',
    fh: 'n/a',
  },
  {
    id: 'pets.wildlife',
    theme: 'pets',
    q: 'Coyotes? Bears? Anything that changes how I let the cat out?',
    who: ['pet', 'all'],
    scope: 'city',
    basis: ['civic', 'social'],
    form: 'text',
    fh: 'n/a',
  },
  {
    id: 'pets.vet',
    theme: 'pets',
    q: 'Vet and emergency vet — how far?',
    who: ['pet'],
    scope: 'city',
    basis: ['place', 'dist'],
    form: 'map',
    fh: 'n/a',
  },
  {
    id: 'pets.rules',
    theme: 'pets',
    q: 'Any HOA or city rule on pets, chickens, fences?',
    who: ['pet'],
    scope: 'home',
    basis: ['zoning', 'listing_text'],
    form: 'text',
    fh: 'n/a',
  },

  // ─── 3.7 Body ──────────────────────────────────────────────────────────
  {
    id: 'body.loop',
    theme: 'body',
    q: 'Is there a safe 5k loop from the front door?',
    who: ['athlete', 'all'],
    scope: 'street',
    basis: ['road', 'place'],
    form: 'map',
    verify: 'Run it',
    dim: 'trails',
    fh: 'n/a',
  },
  {
    id: 'body.bike',
    theme: 'body',
    q: 'Can I bike to anything useful, or is every road a 40 mph arterial?',
    who: ['athlete', 'commuter'],
    scope: 'hood',
    basis: ['road', 'transit'],
    form: 'map',
    dim: 'walkable',
    fh: 'n/a',
  },
  {
    id: 'body.air',
    theme: 'body',
    q: "What's the air like here in wildfire season? Pollen season?",
    who: ['all'],
    scope: 'city',
    basis: ['climate', 'civic'],
    form: 'text',
    fh: 'n/a',
  },
  {
    id: 'body.light',
    theme: 'body',
    q: 'Which rooms get morning light? Where does the afternoon sun land?',
    who: ['all'],
    scope: 'home',
    basis: ['photo', 'assessor'],
    form: 'text',
    verify: 'Visit at 8am and 4pm',
    fh: 'n/a',
  },
  {
    id: 'body.stairs',
    theme: 'body',
    q: 'How many stairs between the car and the kitchen? Between the bedroom and a bathroom?',
    who: ['downsizer', 'accessibility', 'multigen'],
    scope: 'home',
    basis: ['photo', 'listing_text'],
    form: 'number',
    verify: 'Count them',
    fh: 'n/a',
  },

  // ─── 3.8 Nature & seasons ──────────────────────────────────────────────
  {
    id: 'nature.trailhead',
    theme: 'nature',
    q: "What's the trailhead I'd go to on a normal Saturday, not a special one?",
    who: ['all'],
    scope: 'hood',
    basis: ['place', 'dist'],
    form: 'map',
    dim: 'trails',
    fh: 'n/a',
  },
  {
    id: 'nature.november',
    theme: 'nature',
    q: 'What does November look like here?',
    who: ['all'],
    scope: 'city',
    basis: ['climate'],
    form: 'narrative',
    fh: 'n/a',
  },
  {
    id: 'nature.snow',
    theme: 'nature',
    q: "Does this neighbourhood get snow days the city doesn't?",
    who: ['all'],
    scope: 'hood',
    basis: ['climate', 'road'],
    form: 'text',
    dim: 'quiet',
    fh: 'n/a',
  },
  {
    id: 'nature.garden',
    theme: 'nature',
    q: 'Is the yard sunny enough to grow tomatoes?',
    who: ['gardener'],
    scope: 'home',
    basis: ['photo', 'assessor'],
    form: 'text',
    verify: 'Visit at noon, look for shade',
    dim: 'outdoors',
    fh: 'n/a',
  },
  {
    id: 'nature.trees',
    theme: 'nature',
    q: 'Big trees — mine to keep or remove? Overhead lines?',
    who: ['all'],
    scope: 'home',
    basis: ['zoning', 'photo', 'utility'],
    form: 'text',
    dim: 'outdoors',
    fh: 'n/a',
  },
  {
    id: 'nature.water',
    theme: 'nature',
    q: "Where's the water — lake, river, shore — and can I actually get to it?",
    who: ['all'],
    scope: 'city',
    basis: ['place', 'dist'],
    form: 'map',
    dim: 'outdoors',
    fh: 'n/a',
  },
  {
    id: 'nature.view',
    theme: 'nature',
    q: 'Is there a view, and who could build in front of it?',
    who: ['all'],
    scope: 'home',
    basis: ['photo', 'zoning'],
    form: 'text',
    fh: 'n/a',
  },

  // ─── 3.9 Work ──────────────────────────────────────────────────────────
  {
    id: 'work.commute',
    theme: 'work',
    q: "What's the 8am drive to where I work — and the 5:30pm drive back?",
    who: ['commuter'],
    scope: 'home',
    basis: ['dist', 'road', 'transit'],
    form: 'number',
    verify: 'Drive it once at 5:30pm',
    fh: 'n/a',
  },
  {
    id: 'work.toll',
    theme: 'work',
    q: 'Will I be paying tolls to get anywhere on time?',
    who: ['commuter'],
    scope: 'city',
    basis: ['road', 'transit'],
    form: 'number',
    fh: 'n/a',
  },
  {
    id: 'work.transit',
    theme: 'work',
    q: 'Could I get to work without the car, on a bad day?',
    who: ['commuter'],
    scope: 'street',
    basis: ['transit', 'dist'],
    form: 'text',
    dim: 'walkable',
    fh: 'n/a',
  },
  {
    id: 'work.fallback',
    theme: 'work',
    q: "If I lose this job, what's within 30 minutes?",
    who: ['commuter', 'all'],
    scope: 'city',
    basis: ['civic', 'place'],
    form: 'text',
    fh: 'n/a',
  },
  {
    id: 'work.office',
    theme: 'work',
    q: "Is there a room here that's a real home office — door, quiet side, fibre?",
    who: ['remote'],
    scope: 'home',
    basis: ['photo', 'utility', 'road'],
    form: 'text',
    verify: 'Stand in it with the window open',
    dim: 'space',
    fh: 'n/a',
  },
  {
    id: 'work.airport',
    theme: 'work',
    q: "How far is an airport I'd actually fly from?",
    who: ['remote', 'all'],
    scope: 'city',
    basis: ['dist', 'place'],
    form: 'number',
    fh: 'n/a',
  },
  {
    id: 'work.cowork',
    theme: 'work',
    q: 'Coworking or a café that tolerates laptops, within 10 minutes?',
    who: ['remote'],
    scope: 'hood',
    basis: ['place', 'dist'],
    form: 'map',
    dim: 'walkable',
    fh: 'n/a',
  },

  // ─── 3.10 Money over time ──────────────────────────────────────────────
  {
    id: 'money.catch',
    theme: 'money',
    q: "Why is this house priced where it is — what's the catch?",
    who: ['all'],
    scope: 'home',
    // `listing_text`: "motivated seller / potential short sale" is the agent's
    // own statement of the catch (first dry run, 2026-08-29).
    basis: ['market', 'mls', 'assessor', 'road', 'listing_text'],
    form: 'text',
    fh: 'n/a',
  },
  {
    id: 'money.tax',
    theme: 'money',
    q: 'Where are property taxes headed here?',
    who: ['all'],
    scope: 'city',
    basis: ['assessor', 'civic'],
    form: 'timeline',
    fh: 'n/a',
  },
  {
    id: 'money.rent_out',
    theme: 'money',
    q: 'Could I rent out part of this house? Is an ADU allowed?',
    who: ['investor', 'multigen'],
    scope: 'home',
    basis: ['zoning', 'photo'],
    form: 'text',
    fh: 'n/a',
  },
  {
    id: 'money.resale',
    theme: 'money',
    q: 'Will this be easier or harder to sell than the average house here?',
    who: ['all'],
    scope: 'home',
    basis: ['road', 'school', 'market'],
    form: 'text',
    fh: 'n/a',
  },
  {
    id: 'money.trend',
    theme: 'money',
    q: 'Is this neighbourhood peaking, rising, or drifting?',
    who: ['all'],
    scope: 'hood',
    basis: ['market', 'civic', 'project'],
    form: 'text',
    fh: 'n/a',
  },
  {
    id: 'money.insurance',
    theme: 'money',
    q: 'What will an insurer ask about this house?',
    who: ['first_time'],
    scope: 'home',
    basis: ['assessor', 'hazard'],
    form: 'checklist',
    dim: 'move_in',
    fh: 'n/a',
  },
  {
    id: 'money.utilities',
    theme: 'money',
    q: 'What does it cost to heat and cool this place? Electric, gas, oil?',
    who: ['all'],
    scope: 'home',
    basis: ['utility', 'listing_text', 'assessor'],
    form: 'text',
    verify: 'Ask for 12 months of bills',
    fh: 'n/a',
  },
  {
    id: 'money.hoa',
    theme: 'money',
    q: 'Does the HOA fee go up, and what does it actually cover?',
    who: ['all'],
    scope: 'home',
    basis: ['listing_text', 'civic'],
    form: 'text',
    verify: 'Ask for the last 3 years of dues',
    fh: 'n/a',
  },

  // ─── 3.11 Safety, honestly ─────────────────────────────────────────────
  {
    id: 'safety.kind',
    theme: 'safety',
    q: 'What kind of crime actually happens here — car prowls, or something worse?',
    who: ['all'],
    scope: 'city',
    basis: ['crime'],
    form: 'text',
    fh: 'care',
  },
  {
    id: 'safety.dark',
    theme: 'safety',
    q: 'Is it dark on this street at night? Sidewalks?',
    who: ['all'],
    scope: 'street',
    basis: ['road', 'photo'],
    form: 'text',
    verify: 'Drive by at 10pm',
    dim: 'quiet',
    fh: 'n/a',
  },
  {
    id: 'safety.speed',
    theme: 'safety',
    q: 'How fast do cars go past the front door?',
    who: ['family', 'all'],
    scope: 'street',
    basis: ['road', 'project'],
    form: 'number',
    verify: 'Stand out front at 5:30pm',
    dim: 'quiet',
    fh: 'n/a',
  },
  {
    id: 'safety.response',
    theme: 'safety',
    q: 'How far is the fire station? The ER?',
    who: ['all'],
    scope: 'city',
    basis: ['place', 'dist'],
    form: 'number',
    fh: 'n/a',
  },
  {
    id: 'safety.ground',
    theme: 'safety',
    q: "Earthquake, flood, landslide, wildfire — what's the story for this lot?",
    who: ['all'],
    scope: 'home',
    basis: ['hazard'],
    form: 'checklist',
    fh: 'n/a',
  },
  {
    id: 'safety.retrofit',
    theme: 'safety',
    q: 'Has this house been bolted down? Does it need to be?',
    who: ['all'],
    scope: 'home',
    basis: ['assessor', 'hazard'],
    form: 'text',
    verify: 'Ask the inspector',
    dim: 'move_in',
    fh: 'n/a',
  },

  // ─── 3.12 Daily logistics ──────────────────────────────────────────────
  {
    id: 'logistics.turn',
    theme: 'logistics',
    q: 'Can I turn left out of my street at 8am?',
    who: ['all'],
    scope: 'street',
    basis: ['road', 'project'],
    form: 'text',
    verify: 'Stand at the corner, weekday 8:00am',
    dim: 'quiet',
    fh: 'n/a',
  },
  {
    id: 'logistics.cutthrough',
    theme: 'logistics',
    q: 'Is my street a shortcut for other people?',
    who: ['all'],
    scope: 'street',
    basis: ['road', 'project', 'civic'],
    form: 'yes_no',
    dim: 'quiet',
    fh: 'n/a',
  },
  {
    id: 'logistics.guests',
    theme: 'logistics',
    q: 'Where do guests park?',
    who: ['all'],
    scope: 'street',
    basis: ['road', 'photo', 'zoning'],
    form: 'text',
    fh: 'n/a',
  },
  {
    id: 'logistics.plow',
    theme: 'logistics',
    q: 'Do I get plowed? Can I get down the hill in snow?',
    who: ['all'],
    scope: 'street',
    basis: ['climate', 'road', 'civic'],
    form: 'text',
    fh: 'n/a',
  },
  {
    id: 'logistics.trash',
    theme: 'logistics',
    q: 'Trash day, and where does the bin go?',
    who: ['all'],
    scope: 'home',
    basis: ['utility'],
    form: 'text',
    fh: 'n/a',
  },
  {
    id: 'logistics.delivery',
    theme: 'logistics',
    q: 'Can a delivery driver find the door? Same-day Amazon here?',
    who: ['all'],
    scope: 'home',
    basis: ['dist', 'photo'],
    form: 'text',
    fh: 'n/a',
  },
  {
    id: 'logistics.errands',
    theme: 'logistics',
    q: 'Gas, pharmacy, hardware, post office — on the way home or a separate trip?',
    who: ['all'],
    scope: 'hood',
    basis: ['place', 'dist'],
    form: 'map',
    dim: 'walkable',
    fh: 'n/a',
  },
  {
    id: 'logistics.24h',
    theme: 'logistics',
    q: "Where's the nearest 24-hour anything?",
    who: ['all'],
    scope: 'city',
    basis: ['place', 'dist'],
    form: 'number',
    fh: 'n/a',
  },
  {
    id: 'logistics.costco',
    theme: 'logistics',
    q: 'How do I get to Costco, and how bad is it on a Saturday?',
    who: ['all'],
    scope: 'city',
    basis: ['place', 'dist', 'road'],
    form: 'number',
    fh: 'n/a',
  },

  // ─── 3.13 The house, lived in ──────────────────────────────────────────
  {
    id: 'house.noise_in',
    theme: 'house',
    q: 'Where does the noise get in — which room hears the road, the freeway, the planes?',
    who: ['all'],
    scope: 'home',
    basis: ['road', 'dist', 'photo'],
    form: 'text',
    verify: 'Sit in each bedroom at 10pm with the window open',
    dim: 'quiet',
    fh: 'n/a',
  },
  {
    id: 'house.water',
    theme: 'house',
    q: 'Where does the water go in a hard rain?',
    who: ['all'],
    scope: 'home',
    basis: ['photo', 'assessor', 'hazard'],
    form: 'text',
    verify: 'Visit during rain; look at the basement corners',
    dim: 'move_in',
    fh: 'n/a',
  },
  {
    id: 'house.era',
    theme: 'house',
    q: 'It was built when it was built — what does that mean I should inspect?',
    who: ['first_time', 'all'],
    scope: 'home',
    basis: ['assessor'],
    form: 'checklist',
    verify: 'Give this list to the inspector',
    dim: 'move_in',
    fh: 'n/a',
  },
  {
    id: 'house.addition',
    theme: 'house',
    q: 'Was something added to this house, and was it permitted?',
    who: ['all'],
    scope: 'home',
    basis: ['assessor', 'mls'],
    form: 'text',
    verify: 'Ask for permit history',
    dim: 'move_in',
    fh: 'n/a',
  },
  {
    id: 'house.ev',
    theme: 'house',
    q: 'Can I charge an EV here? Put up solar?',
    who: ['all'],
    scope: 'home',
    basis: ['photo', 'utility', 'assessor'],
    form: 'text',
    fh: 'n/a',
  },
  {
    id: 'house.heat',
    theme: 'house',
    q: 'Will I survive a July heat wave in this house?',
    who: ['all'],
    scope: 'home',
    basis: ['listing_text', 'photo', 'climate'],
    form: 'text',
    fh: 'n/a',
  },
  {
    id: 'house.parents',
    theme: 'house',
    q: 'Could my parents live downstairs with their own door?',
    who: ['multigen'],
    scope: 'home',
    basis: ['photo', 'listing_text', 'zoning'],
    form: 'text',
    fh: 'n/a',
  },
  {
    id: 'house.signal',
    theme: 'house',
    q: 'Cell signal inside, by carrier?',
    who: ['remote', 'all'],
    scope: 'home',
    basis: ['utility'],
    form: 'text',
    verify: 'Check your phone in the basement',
    fh: 'n/a',
  },
  {
    id: 'house.groceries',
    theme: 'house',
    q: 'How far from the car to the kitchen with groceries?',
    who: ['downsizer', 'all'],
    scope: 'home',
    basis: ['photo'],
    form: 'number',
    fh: 'n/a',
  },
  {
    id: 'house.storage',
    theme: 'house',
    q: 'Where does the stuff go — bikes, skis, the second fridge?',
    who: ['family'],
    scope: 'home',
    basis: ['photo', 'listing_text'],
    form: 'text',
    dim: 'space',
    fh: 'n/a',
  },
  {
    id: 'house.fibre',
    theme: 'house',
    q: 'Fibre to this address, or cable?',
    who: ['remote', 'all'],
    scope: 'home',
    basis: ['utility'],
    form: 'yes_no',
    fh: 'n/a',
  },

  // ─── 3.14 Sound & smell ────────────────────────────────────────────────
  {
    id: 'sound.planes',
    theme: 'sound',
    q: 'Am I under a flight path?',
    who: ['all'],
    scope: 'home',
    basis: ['dist', 'civic', 'social'],
    form: 'text',
    verify: 'Sit outside on a clear evening',
    dim: 'quiet',
    fh: 'n/a',
  },
  {
    id: 'sound.freeway',
    theme: 'sound',
    q: 'Will I hear the freeway at night?',
    who: ['all'],
    scope: 'home',
    basis: ['dist', 'road'],
    form: 'text',
    verify: '10pm, windows open',
    dim: 'quiet',
    fh: 'n/a',
  },
  {
    id: 'sound.events',
    theme: 'sound',
    q: "Friday night football, church bells, a school bell, a train horn — what's on the schedule?",
    who: ['all'],
    scope: 'hood',
    basis: ['place', 'dist', 'social'],
    form: 'text',
    dim: 'quiet',
    fh: 'n/a',
  },
  {
    id: 'sound.sirens',
    theme: 'sound',
    q: 'Am I on the route to the hospital or the fire station?',
    who: ['all'],
    scope: 'street',
    basis: ['road', 'place'],
    form: 'yes_no',
    dim: 'quiet',
    fh: 'n/a',
  },
  {
    id: 'sound.smell',
    theme: 'sound',
    q: "Anything I'd smell — treatment plant, dairy, brewery, mill?",
    who: ['all'],
    scope: 'hood',
    basis: ['place', 'social'],
    form: 'text',
    fh: 'n/a',
  },

  // ─── 3.15 Identity & future ────────────────────────────────────────────
  {
    id: 'identity.signal',
    theme: 'identity',
    q: 'What does living here say — practical, quiet money, up-and-coming, retiree calm?',
    who: ['all'],
    scope: 'hood',
    basis: ['market', 'civic', 'social'],
    form: 'narrative',
    dim: 'hip',
    fh: 'care',
  },
  {
    id: 'identity.first',
    theme: 'identity',
    q: 'Would I be the first of my kind here, or one of many?',
    who: [],
    scope: 'hood',
    basis: [],
    form: 'text',
    fh: 'never',
  },
  {
    id: 'future.construction',
    theme: 'future',
    q: "What's under construction within a mile, and until when?",
    who: ['all'],
    scope: 'hood',
    basis: ['project'],
    form: 'timeline',
    fh: 'n/a',
  },
  {
    id: 'future.transit',
    theme: 'future',
    q: 'Is transit coming? When?',
    who: ['all'],
    scope: 'hood',
    basis: ['transit', 'project'],
    form: 'timeline',
    dim: 'walkable',
    fh: 'n/a',
  },
  {
    id: 'future.nextdoor',
    theme: 'future',
    q: "What's the zoning going to allow next door?",
    who: ['all'],
    scope: 'home',
    basis: ['zoning', 'civic'],
    form: 'text',
    fh: 'n/a',
  },
  {
    id: 'future.plan',
    theme: 'future',
    q: 'What does the city say this neighbourhood becomes in twenty years?',
    who: ['all'],
    scope: 'hood',
    basis: ['civic'],
    form: 'text',
    fh: 'n/a',
  },
];

/** Questions the generator may answer and the UI may show. */
export const ASKABLE_QUESTIONS: readonly QuestionDef[] = QUESTIONS.filter((q) => q.fh !== 'never');

const BY_ID: ReadonlyMap<string, QuestionDef> = new Map(QUESTIONS.map((q) => [q.id, q]));

/** Lookup by id. `undefined` for an id the bank does not carry. */
export function questionById(id: string): QuestionDef | undefined {
  return BY_ID.get(id);
}
