-- Cached locality map thumbnails for the listing card.
--
-- Why cache instead of hitting Static Maps per render: the card's map is a
-- FIXED picture of a FIXED coordinate. Re-fetching it on every card render costs
-- a billable Static Maps request each time and needs the API key on the client
-- (an `EXPO_PUBLIC_*` key is inlined into the JS bundle and is therefore
-- extractable). Rendering it once server-side into Storage removes both: the
-- phone loads a plain public image URL and the key never leaves this host.
--
-- `map_url` is a public Storage URL, so readers need no signing and no key.
-- Nullable + additive: a listing with no cached tile just renders no map.
alter table public.listings
  add column if not exists map_url text,
  add column if not exists map_cached_at timestamptz;

comment on column public.listings.map_url is
  'Public Storage URL of the pre-rendered Static Maps thumbnail for (lat,lng). Generated by scripts/backfill_listing_maps.py. Null → card renders no map.';
comment on column public.listings.map_cached_at is
  'When map_url was generated. Re-render when lat/lng changes or the styling is revised.';
